### ISSUE TITLE
make Expectations work in Clojurescript

### ISSUE THREAD

**Issue by yayitswei** [jaycfields/expectations#11]
Since it could really use a good testing library. 

How hard would it be to factor out all of the JVM bits? I could take a stab at it but would need a bit of direction to get started.

**Comment by imikushin** [comment]
Hi, I'm definitely interested in this. Would you accept a PR (with a cross compiled version) usable from both Clojure and ClojureScript?

**Comment by jaycfields** [comment]
Hi Ivan, I'm hesitant, since I'm still not doing anything with ClojureScript, but I'm not completely against it. If the impact isn't too large, then I would like to help make things work.

**Comment by imikushin** [comment]
Great! 
There are a couple alteratives: 
- One approach could be to make a ClojureScript port - like [clojurescript.test](https://github.com/cemerick/clojurescript.test). This can be a separate project (called, say, `cljs.expect`). 
- Another one would be to use [cljx](https://github.com/lynaghk/cljx) to cross-compile for both Clojure and ClojureScript. This requires a bit more work (at first), but promises less effort to sync features and fixes for both environments. I want to go this path. 

What do you think?

**Comment by jaycfields** [comment]
I think we should definitely give the the latter approach a shot. We can always fall back to the first approach if things get too complicated.

**Comment by imikushin** [comment]
Okay, cool. I'll try to put it together in the next few days, then.

**Comment by imikushin** [comment]
It's been quite a few days, but here we are. I hope it's worth a minor release version bump (to 2.1).
Clojure code had to be refactored a bit to become more cross-plaform, macro-generated var naming had to be fixed (get rid of `gensym`) as well as compile time var user metadata support in ClojureScript upstream. The result: we can now use Expectations from ClojureScript:
```clojure
(ns my-lib.test
  (:require-macros [expectations.cljs :as ecljs])
  (:require [my-lib.expectations-options]
            [my-lib.core-test]
            [my-lib.util-test]))

(defn -main []
  (ecljs/run-all-tests))

(enable-console-print!)
(set! *main-cli-fn* -main)
```
I'm looking forward to know what you think!

**Comment by jaycfields** [comment]
pretty cool, I was looking over the commit this morning. I'll do a bit of
experimenting, but I don't see any reason I wouldn't merge.

On Mon, Feb 23, 2015 at 7:35 AM, Ivan Mikushin <notifications@github.com>
wrote:

> It's been quite a few days, but here we are. I hope it's worth a minor
> release version bump (to 2.1).
> Clojure code had to be refactored a bit to become more cross-plaform,
> macro-generated var naming had to be fixed (get rid of gensym) as well as
> compile time var user metadata support in ClojureScript upstream. The
> result: we can now use Expectations from ClojureScript:
>
> (ns my-lib.test
>   (:require-macros [expectations.cljs :as ecljs])
>   (:require [my-lib.expectations-options]
>             [my-lib.core-test]
>             [my-lib.util-test]))
>
> (defn -main []
>   (ecljs/run-all-tests))
>
> (enable-console-print!)
> (set! *main-cli-fn* -main)
>
> I'm looking forward to know what you think!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaycfields/expectations/issues/11#issuecomment-75533943>
> .
>



-- 
Any fool can write a test that helps them today. Good programmers write
tests that help the entire team in the future. http://wewut.com

**Comment by ptaoussanis** [comment]
Haven't looked at the PR in particular, but Cljs support would be really welcome!

**Comment by imikushin** [comment]
A tiny ClojureScript sample project: https://github.com/imikushin/expectations-hello-cljs

**Comment by jaycfields** [comment]
Thanks to Ivan, I think this is ready for use. (well, it's been ready for use, but I hadn't published it to clojars till now)

Please let me know if you use it and things don't work.
