### ISSUE TITLE
allow :in-context option to be namespace specific

### ISSUE THREAD

**Issue by Whoops** [jaycfields/expectations#45]
I'm experimenting with porting a test suite over to expectations, which has gone well. I have a single module responsible for all database interactions, and only tests in this namespace are allowed to touch the database. Before each test I setup a fixture to ensure the database is in a known state. This works fine:

``` clojure
;; db_test.clj
(defn run-with-fixture
  "rebind a var, expecations are run in the defined context"
  {:expectations-options :in-context}
  [work]
  (install-fixture)
  (work))
```

The problem is that this causes the fixture to be setup for _all_ test, not just those defined in the `db` namespace significantly slowing down the run. So far the only workaround I have is to explicitly exclude the `db` namespace via regex when running `lein expectations`, but this is awkward as it involves two runs to test everything, and doesn't appear to work with `autoexpect`.

**Comment by coltnz** [comment]
Is there any way to run setup/teardown at per-ns level rather than var or the whole test run?

**Comment by jaycfields** [comment]
There are no expectations hooks for per-ns setup/teardown. You could do it in-context by detecting the namespace (if you only need a few); otherwise, you'll have to use helper functions.
