### ISSUE TITLE
Creating complex matchers using custom predicates

### ISSUE THREAD

**Issue by squeedee** [jaycfields/expectations#48]
This is not so much an issue than a use-case and an appeal for some code review.

I wanted to write a visual expect/diff test for a rogue-like map. The best I could come up with was this custom predicate.
https://github.com/squeedee/mapper/blob/master/test/mapper/csg/operators_test.clj#L22-L47

First, it might be of some use to see what I tried to achieve. I don't know :D 
Second, have I approached this in a wholly unidiomatic way? Is there a more sensible way of testing these expectations or writing the predicate?

Any feedback would be appreciated.

**Comment by jaycfields** [comment]
CustomPred is used mostly (exclusively) for formatting error messages when things fail. If you're looking to do that, then I think your solution looks good. If you only really care about the expect-fn you could just use a plain old function.

Based on the complexity of what you're doing, I assume the custom failure message is really helpful.

**Comment by squeedee** [comment]
Indeed it is helpful:

Replacing xor with or, for example.

```
(expect
 (->NoDiff map-dimensions expected-string-map)
 subtraction-map-fn)

           expected ->
..........
.#####....
.#####....
.###..###.
.###..###.
....#####.
....#####.
..........
           actual ->
..........
.#####....
.#####....
.########.
.########.
....#####.
....#####.
..........
           Visual diff ->
..........
.#####....
.#####....
.###!!###.
.###!!###.
....#####.
....#####.
..........
```
