### ISSUE TITLE
Using expectations with boot-clj

### ISSUE THREAD

**Issue by emiln** [jaycfields/expectations#52]
Hi, Jay.

I've just started using [boot-clj](http://boot-clj.com) and expectations, and I am wondering how difficult it would be to create a boot task to run tests defined using expectations. The thing is I don't really understand how expectations work. So far I've just been using `expect` and reveling in how wonderfully it works with [lein-expectations](/gar3thjon3s/lein-expectations) without worrying about how it all works under the hood.

My question is therefore what I'll need to do in order to actually run the expectations tests defined in a given namespace. What does expect actually produce, and how to I turn it into text like lein-expectations?

Thanks in advance.

**Comment by imikushin** [comment]
Hi Emil,
Here's how you can run expectations from your Clojure code:
`(expectations/run-all-tests)` runs all expectations in all accessible namespaces.
`(expectations/run-all-tests #"re")` runs only the expectations from the namespaces satisfying the regular expression. 
There's also `(expectations/run-tests namespaces)` which runs expectations defined in the supplied namespaces (must be a collection). 
These would probably be straightforward to call from a Boot task or script.

**Comment by emiln** [comment]
That's really simple and approachable. Thanks a lot, @imikushin! I'll give that a try when I am off work.

**Comment by jaycfields** [comment]
I've not used boot-clj (though I've been planning to check it out); hpoefully, the info Ivan provided will be enough to get you started. There's (possibly) two other things worth knowing:
- expectations are run on shutdown, unless explicitly told not to.
- expectations are only run once. When you load a file with expectations in it they'll be defined as vars, and only evaluated once. If you want to "rerun" the expectations you'll have to define new vars, which should be as easy to reloading the file.

**Comment by imikushin** [comment]
Yeah, about auto running on shutdown: I actually often run expectations with `lein test` since it loads all test namespaces in a project (scanning for test vars) and thus defines expectation vars which are happily executed and reported by the shutdown hook :)

**Comment by emiln** [comment]
Thanks a lot, both of you!

This was very easy to get going. The following is a dumb, hard-coded, but fully working example of running the tests in the file `test/logic_test.clj`, containing the namespace `logic-test`, making use of the tip about expectations running on shutdown:

```clojure
(deftask expectations
  "Run tests"
  []
  (set-env! :source-paths #{"test"})
  (use 'logic-test))
```

My next question is then whether you have some tips on how to `(use)` just the namespaces actually defined in my `test` folder? Or whether there's a more sensible direction to take this in. Currently my best bet it to weed out the result of calling `(all-ns)`, which even in the above example contains a rather daunting 47 namespaces.

**Comment by jaycfields** [comment]
I'm not sure what the "right" answer is, but you could filter (all-ns) with
a pred checking for any var with the expectations meta - and only 'use
those.

On Mon, Mar 2, 2015 at 4:29 PM, Emil Holm Nauerby <notifications@github.com>
wrote:

> Thanks a lot, both of you!
>
> This was very easy to get going. The following is a dumb, hard-coded, but
> fully working example of running the tests in the file test/logic_test.clj,
> containing the namespace logic-test, making use of the tip about
> expectations running on shutdown:
>
> (deftask expectations
>   "Run tests"
>   []
>   (set-env! :source-paths #{"test"})
>   (use 'logic-test))
>
> My next question is then whether you have some tips on how to (use) just
> the namespaces actually defined in my test folder? Or whether there's a
> more sensible direction to take this in. Currently my best bet it to weed
> out the result of calling (all-ns), which even in the above example
> contains a rather daunting 47 namespaces.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaycfields/expectations/issues/52#issuecomment-76829314>
> .
>



-- 
Any fool can write a test that helps them today. Good programmers write
tests that help the entire team in the future. http://wewut.com

**Comment by imikushin** [comment]
In the boot task, if `(all-ns)` can find all namespaces (even those you didn't explicitly `require`), I'd disable the shutdown hook with `(expectations/disable-run-on-shutdown)` and run them in the task with `(run-all-tests)`: with the shutdown hook enabled and the `use` hack utilizing it, you won't actually run tests until shutdown. 
This doesn't work if you're trying to construct a continually running boot pipeline. 
You can constraint namespaces with a regexp if you wish.

**Comment by jaycfields** [comment]
Ivan's solution sounds superior, I would start there. :)

On Wednesday, March 4, 2015, Ivan Mikushin <notifications@github.com> wrote:

> In the boot task, if (all-ns) can find all namespaces (even those you
> didn't explicitly require), I'd disable the shutdown hook with
> (expectations/disable-run-on-shutdown) and run them in the task with
> (run-all-tests): with the shutdown hook enabled and the use hack
> utilizing it, you won't actually run tests until shutdown.
> This doesn't work if you're trying to construct a continually running boot
> pipeline.
> You can constraint namespaces with a regexp if you wish.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaycfields/expectations/issues/52#issuecomment-77094737>
> .
>


-- 
Any fool can write a test that helps them today. Good programmers write
tests that help the entire team in the future. http://wewut.com

**Comment by jaycfields** [comment]
I'm assuming this is good to go. Please let me know if you ran into any issues.

**Comment by seancorfield** [comment]
It's only a snapshot release right now but I'll add options and features as folks request: https://clojars.org/seancorfield/boot-expectations
