### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by simax** [jaycfields/expectations#53]
I'm trying to use `lein cloverage` with expectations. Although it appears to have run, and produced html files. Only the function signatures are highlighted green, the lines of code in the function body are all red, even though the functions have been called by the test. Is `expectations` compatible with `lein-cloverage`? If not, are there any other coverage tools that work with `expectations`

**Comment by jaycfields** [comment]
I've never used lein coverage, but I am a bit curious. I'll try to take a
look in the next few days.

If you're relying on expectations to be run via the lein test task then the
timing may be off. As Ivan recently pointed out on another ticket, the
tests aren't run till shutdown by default. If that's the issue it should
(hopefully) be easy to fix with an explicit call to run tests.

On Tuesday, March 3, 2015, Simon Lomax <notifications@github.com> wrote:

> I'm trying to use lein cloverage with expectations. Although it appears
> to have run, and produced html files. Only the function signatures are
> highlighted green, the lines of code in the function body are all red, even
> though the functions have been called by the test. Is expectations
> compatible with lein-cloverage? If not, are there any other coverage
> tools that work with expectations
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaycfields/expectations/issues/53>.
>


-- 
Any fool can write a test that helps them today. Good programmers write
tests that help the entire team in the future. http://wewut.com

**Comment by simax** [comment]
Jay,

In case it helps in your investigations, the set up I used was to add `[lein-cloverage "1.0.2"]` to the `:plugins` section of my `./lein/profiles.clj`. I have `lein autoexpect` running and then at some stage I run `lein cloverage`.

Regards,
Simon

**Comment by jaycfields** [comment]
Hi Simon,
I finally got a chance to look at this. I'm pretty sure it's as I expected - the tests are running as part of shutdown and the coverage has already been generated at that point. You may be able to work around this with something like the following

```clj
(clojure.test/deftest run-expectations-as-part-of-clojure-test
  (expectations/disable-run-on-shutdown)
  (expectations/run-all-tests))
```
You may also need to require (or load) all your expectations namespaces. You shouldn't but I thought it was worth mentioning.

The longer term fix is to get cloverage to support expectations, but I can't speak to whether or not they'd have any interest.
