### ISSUE TITLE
Timeout for tests?

### ISSUE THREAD

**Issue by magnars** [jaycfields/expectations#56]
Hello! Thanks for a great test framework. This is what I wrote to some colleagues:

> Halleluja, here finally is the test framework for Clojure: http://jayfields.com/expectations/index.html Consise syntax, fast autotests, good feedback. <3

Now, I am testing some core.async code, and it is easy to create tests that hang indefinitely. Can I specify a timeout period in some way?

**Comment by imikushin** [comment]
@magnars can you give some test cases? I realize it's very easy to hang async code, but working with some concrete examples is much simpler than guessing what could be your situation. 

Now I can only guess what it is, but you could expect a concrete value and encapsulate the async code. E.g. like this:
```clojure
(expect
  :expected-value   ; replace with something you expect
  (let [test-agent (agent {})]
    (if (await-for 1000 ;milliseconds  
                   (send-off test-agent (fn [agent-state]
                                          ; potentially deadlocking code here
                                          :test-value       ; replace with something your code will have produced
                                          ))) 
      @test-agent)))
```

**Comment by magnars** [comment]
I'm so used to test frameworks handling async and timeouts for me, I didn't even consider whipping up something myself. :blush: Thanks, I'll go with something along those lines!

**Comment by imikushin** [comment]
I'd be happy to add some async goodness to Expectations. Can you point to some good examples you like in other frameworks?

**Comment by jaycfields** [comment]
I'm watching :)

I'd be up for adding anything that makes sense as well. Or perhaps another namespace (maybe 'expectations.async) that has helper fns for things that are commonly done.

**Comment by magnars** [comment]
Well, most of my TDD experience is from JavaScript, where async is done quite differently with callbacks. But I guess the feature I needed at this time, is this:

- if a test takes too long to run, it is aborted and counted as an error.
