### ISSUE TITLE
autoexpect does not detect changes in .cljc files

### ISSUE THREAD

**Issue by magnars** [jaycfields/expectations#57]
Running `lein autoexpect` works fine with `.cljc` files in Clojure 1.7.0-beta3, but any changes are not detected. Touching a `.clj` file will rerun the tests, but the `.cljc` files are not recompiled.

If you have a general idea of how to fix this, but not the time to do so, I'd be willing to work on a pull request with a point in the right direction. :)

**Comment by jaycfields** [comment]
I'm not sure how actively Jake uses expectations these days, but I'm sure he'd want to fix things in https://github.com/jakemcc/lein-autoexpect

**Comment by magnars** [comment]
Oh, look at that. Sorry about the mis-issue!

**Comment by jaycfields** [comment]
no worries, glad you're using expectations - happy to help. :)

**Comment by magnars** [comment]
I'm glad I'm using expections too, it's quite excellent. Thanks for your work on it. :)

**Comment by imikushin** [comment]
@magnars btw, you don't need lein-autoexpect to rerun tests. just run
```
lein cljsbuild auto test
```
To configure lein-cljsbuild apropriately, see example here: https://github.com/jaycfields/expectations/blob/master/CHANGELOG.md

**Comment by magnars** [comment]
Thanks Ivan, good tip! But these are the Clojure tests I'm running. :)
