### ISSUE TITLE
JUnit test runner requires Java 1.8

### ISSUE THREAD

**Issue by loomis** [jaycfields/expectations#58]
The packaged version of expectations on clojars was compiled with Java 1.8.  This poses a problem on Ubuntu 14.04 where the default version of Java is still 1.7.  Is the requirement to use Java 1.8 intentional or would a release with Java 1.7 byte code be possible?

**Comment by jaycfields** [comment]
With Java 7 being EOL, we've stopped supporting it. I could possibly be
convinced to go back to 1.7, but I'm not looking to support that version
much longer.

On Sunday, May 31, 2015, Charles (Cal) Loomis <notifications@github.com>
wrote:

> The packaged version of expectations on clojars was compiled with Java
> 1.8. This poses a problem on Ubuntu 14.04 where the default version of Java
> is still 1.7. Is the requirement to use Java 1.8 intentional or would a
> release with Java 1.7 byte code be possible?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaycfields/expectations/issues/58>.
>


-- 
Any fool can write a test that helps them today. Good programmers write
tests that help the entire team in the future. http://wewut.com

**Comment by loomis** [comment]
Thanks for the response.  Looking at the backport requests for Java 1.8 on Ubuntu 14.04, it doesn't look like it will arrive officially on Ubuntu 14.04 any time soon, so it probably isn't worth locking expectations into 1.7.  As Ubuntu isn't our primary platform anyway, I'll just mark it as unsupported until 1.8 is available.
