### ISSUE TITLE
Async tests

### ISSUE THREAD

**Issue by magnars** [jaycfields/expectations#59]
Hello! Ref #56,

> I'd be happy to add some async goodness to Expectations. Can you point to some good examples you like in other frameworks?

Inspired by how async is done in a few popular JavaScript test frameworks, maybe it could look like this?

```clj
(expect :expected-value
        (with-async-callback [done]
          (do-some-async-things
           (fn [result] ;; callback function
             (done result)))))
```

So, the `:expected-value` is compared to the value passed to the given `done` function, once that returns. It would also be nice with a timeout if `done` is not called within a reasonable time.

Thoughts?

**Comment by jaycfields** [comment]
Hi,

Working through some tough issues at work this week, but I'm hoping to get
to this shortly. Sorry for the delay.

On Mon, Jun 1, 2015 at 2:40 AM, Magnar Sveen <notifications@github.com>
wrote:

> Hello! Ref #56 <https://github.com/jaycfields/expectations/issues/56>,
>
> I'd be happy to add some async goodness to Expectations. Can you point to
> some good examples you like in other frameworks?
>
> Inspired by how async is done in a few popular JavaScript test frameworks,
> maybe it could look like this?
>
> (expect :expected-value
>         (with-async-callback [done]
>           (do-some-async-things
>            (fn [result] ;; callback function
>              (done result)))))
>
> So, the :expected-value is compared to the value passed to the given done
> function, once that returns. It would also be nice with a timeout if done
> is not called within a reasonable time.
>
> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaycfields/expectations/issues/59>.
>



-- 
Any fool can write a test that helps them today. Good programmers write
tests that help the entire team in the future. http://wewut.com

**Comment by magnars** [comment]
No worries at all, I'm using core.async to remove the async-ness of my tests at the moment. :)

**Comment by jaycfields** [comment]
I've been letting this rest on a background thread of mine, thinking about different options. What do you think about a solution that uses only clojure.core constructs? For example

```clj
(expect :something
 (deref 
  (doto (promise)
    (->> (partial deliver) (do-some-async-things))) 
  100 :timeout))
```

It's more verbose, but everyone familiar with clojure should be able to read it without having to learn any special expectations syntax.

**Comment by jaycfields** [comment]
closing this for now, but happy to re-open if your interest in the issue rises again.

(I'm hoping the core.async usage removed the need) :)
