### ISSUE TITLE
side-effects with multiple functions to track

### ISSUE THREAD

**Issue by muhuk** [jaycfields/expectations#61]
It would be nice to distinguish which function is called when `side-effects` is used with multiple functions.

Assuming this code:

    (defn g [_] nil)
    (defn h [_] nil)
    (defn f []
      (g :a)
      (h :b)
      (g :c))	

The expected value doesn't tell which functions is called:

    (expect [[:a] 
             [:b] 
             [:c]]
            (side-effects [g h]
              (f)))

-----

I think this and #49 would make expectations more likely to be preferred over Midje. I would write the same test as such:

    (fact "..."
      (f) => anything
      (provided (g :a) => irrelevant
                (h :b) => irrelevant
                (g :c) => irrelevant))

**Comment by muhuk** [comment]
My point is not comparing different test frameworks but to mention that *easy mocking* is, IMO, an important feature. Expectations is beautiful.

**Comment by jaycfields** [comment]
sorry, this completely fell off my radar. I'll try to take a look in the next few days

**Comment by muhuk** [comment]
Four minutes no replies then dis!!!!!11111

I want my money back!

LOL. JK. Take care.

**Comment by jaycfields** [comment]
:)

I meant #49 mostly. I'll look at both in parallel. Hopefully in the next few days. Headed to a wedding tomorrow and traveling all weekend. Next week though, I'll see what I can figure out.

**Comment by jaycfields** [comment]
putting my thoughts into #49
