### ISSUE TITLE
clojars version requires Java 8 Runtime

### ISSUE THREAD

**Issue by roytruelove** [jaycfields/expectations#63]
Getting the following when trying to run using the jUnit wrapper:

`expectations/junit/ExpectationsTestRunner$TestSource : Unsupported major.minor version 52.0`

Which refers to Java 8.  Can it instead be compiled with Java 6, since that's the Clojure 1.6 / 1.7 JDK version?

**Comment by jaycfields** [comment]
We made the decision to upgrade to Java 8 once Oracle moved past Java 7 End of Life*. I know this caused a few people some inconvenience, I am sorry for that, but at this time we're not willing to go back to an older version of Java.

* http://www.oracle.com/technetwork/java/eol-135779.html
