### ISSUE TITLE
Breaking update in minor 2.1.4 release?

### ISSUE THREAD

**Issue by ptaoussanis** [jaycfields/expectations#65]
Hi Jay,

Just wondering if you'd perhaps be open to possibly trying to avoid breaking changes on 0.0.x releases? Might be a convenient way for lib users to know whether an update requires migration or not?

Thanks again for all your work on Expectations! Cheers :-)

**Comment by jaycfields** [comment]
Yeah, definitely. Sorry for the breaking change in a minor version, it's laziness not an intentional disregard for common sense. The result is the same though, I'll try to do better going forward.

**Comment by ptaoussanis** [comment]
No problem :-)
