### ISSUE TITLE
*ns* has the wrong value in test

### ISSUE THREAD

**Issue by mmower** [jaycfields/expectations#66]
This may be nothing to do with expectations but I'm not sure where else to start.

In my test code I have

`(ns fate.core-test
    (:require [expectations :refer :all]
              [fate.core :refer :all]
              [com.stuartsierra.dependency :as dep]))`

and later I

`(expect nil *ns*)`

expecting it to fail telling me my namespace is something like

`#object[clojure.lang.Namespace 0x2440eb85 "fate.core-test"]`

but, instead I get

`#object[clojure.lang.Namespace 0x48531d5 "user"]`

Which seems to be suggesting that the test is somehow changing the namespace, or bypassing the setting of the namespace, or something is going on that I don't understand.

Any ideas why this might be the case?

So far as I can see using `(ns foo)` automatically sets the value of `*ns*` to foo so i'm a bit baffled.

m/

**Comment by jaycfields** [comment]
Hi Matt,
This is due to compile vs runtime. Anything in expect should be evaluated at runtime, where *ns* definitely differs from compile time. If you want the *ns* you have to let or def it outside of the expect and reference the var within the expect.

**Comment by mmower** [comment]
Thanks Jay. For some reason I had assumed that the test code would be run in the context of the namespace that defines it but, as soon as you point it out, I realise the folly of making the assumption. Thanks for taking the time to explain it. Best, m/

**Comment by jaycfields** [comment]
No worries, glad it makes sense :)
