### ISSUE TITLE
Replace cljx with cljc

### ISSUE THREAD

**Issue by bbatsov** [jaycfields/expectations#67]
Now that Clojure 1.7 and 1.8 are out it might be a good idea to start using cljc from Clojure 1.7 instead.

**Comment by jaycfields** [comment]
Unfortunately I'm still not using cljs, so we really have two ways forward.

1. Someone who is using cljs can take the lead on updating what we have.
2. I remove the cljs support from expectations.

I'm hoping we can go down the first path, but I've yet to find a volunteer.

**Comment by imikushin** [comment]
Hey @jaycfields, sorry for not showing up for long (been a bit much too busy for a while). I think I can give it another shot now and help with the CLJX->CLJC transition. Hopefully this time I'll also update the docs for usage with CLJS.

**Comment by jaycfields** [comment]
@imikushin :+1:

**Comment by plexus** [comment]
this can be closed.

**Comment by jaycfields** [comment]
thx for the PRs.

**Comment by plexus** [comment]
yeah I'm done for now :) learned a couple new things. Thanks for this project!
