### ISSUE TITLE
Add documentation for usage with Boot?

### ISSUE THREAD

**Issue by seancorfield** [jaycfields/expectations#76]
Would you be open to adding "getting started" documentation for Boot users?

I'd be happy to provide this (as the author of https://github.com/seancorfield/boot-expectations).

How would you prefer to receive that? As a PR on the gh-pages branch here, or is that generated from source Markdown somewhere else?

**Comment by jaycfields** [comment]
absolutely, and a PR on gh-pages would be perfect

**Comment by seancorfield** [comment]
I'll try to get that to you next week then. Thank you!

**Comment by jaycfields** [comment]
np, thx for the contributions.

**Comment by seancorfield** [comment]
Done. Sorry it took me a while.

**Comment by jaycfields** [comment]
awesome. merged. Thanks Sean
