### ISSUE TITLE
Expectations 2.1.6 does not run in a Clojure-only project

### ISSUE THREAD

**Issue by seancorfield** [jaycfields/expectations#77]
This exception is produced:
```
Retrieving expectations-2.1.6.jar from https://clojars.org/repo/
Retrieving joda-time-2.9.3.jar from https://repo1.maven.org/maven2/
             clojure.lang.ExceptionInfo: java.io.FileNotFoundException: Could not locate cljs/analyzer__init.class or cljs/analyzer.clj on classpath., compiling:(expectations/platform.clj:1:1)
    data: {:file
           "/var/folders/p1/30gnjddx6p193frh670pl8nh0000gn/T/boot.user852945197313464727.clj",
           :line 185}
java.util.concurrent.ExecutionException: java.io.FileNotFoundException: Could not locate cljs/analyzer__init.class or cljs/analyzer.clj on classpath., compiling:(expectations/platform.clj:1:1)
clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could not locate cljs/analyzer__init.class or cljs/analyzer.clj on classpath., compiling:(expectations/platform.clj:1:1)
          java.io.FileNotFoundException: Could not locate cljs/analyzer__init.class or cljs/analyzer.clj on classpath.
```

**Comment by jaycfields** [comment]
@plexus any guesses?

**Comment by seancorfield** [comment]
FWIW, I verified with a clean project:

    lein new testexp

Edit `project.clj` to look like this:
```
(defproject testexp "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :plugins [[lein-expectations "0.0.7"]]
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [expectations "2.1.6"]])
```
and `test/testexp/core_test.clj` to look like this:
```
(ns testexp.core-test
  (:require [expectations :refer :all]
            [testexp.core :refer :all]))

(expect 0 1)
```

**Comment by seancorfield** [comment]
Should this line have `cljs`, not `clj`?

https://github.com/jaycfields/expectations/blob/master/src/cljc/expectations/platform.cljc#L4

**Comment by jaycfields** [comment]
I'm guessing yes, committed. I'll do another release. Let me read some docs to see how to snapshot, so we don't burn through release numbers unnecessarily.

**Comment by jaycfields** [comment]
2.1.7 is out there. I tried to release it as alpha, but I don't think that really worked.

**Comment by seancorfield** [comment]
Something about how you prepare the build isn't working: the `expectations/platform.clj` file in 2.1.7 still has:
```
(ns expectations.platform
  (:refer-clojure :exclude [bound? format ns-name])
  (:require       [clojure.pprint :as pprint]
                  [cljs.analyzer]
                        
                               )
        (:import (clojure.lang Agent Atom Ref)))
```

**Comment by jaycfields** [comment]
hmm, I'm literally doing nothing but `lein release` (and `lein release :alpha` for the last one).

We may have to wait on European hours for @plexus tomorrow.

**Comment by seancorfield** [comment]
I tried to build the repo locally with `lein jar` to see if I can debug it but I get these errors:
```
Compiling 2 source files to /Developer/workspace/expectations/target/classes
/Developer/workspace/expectations/src/java/expectations/junit/ExpectationsTestRunner.java:3: error: package clojure.lang does not exist
import clojure.lang.RT;
                   ^
/Developer/workspace/expectations/src/java/expectations/junit/ExpectationsTestRunner.java:13: error: cannot find symbol
        RT.loadResourceScript("expectations/junit/runner.clj");
        ^
  symbol:   variable RT
  location: class ExpectationsTestRunner
/Developer/workspace/expectations/src/java/expectations/junit/ExpectationsTestRunner.java:14: error: cannot find symbol
        clojureRunner = (Runner) RT.var("expectations.junit.runner", "create-runner").invoke(source);
                                 ^
  symbol:   variable RT
  location: class ExpectationsTestRunner
3 errors
Compilation of Java sources(lein javac) failed.
```
Do I need something in my `~/.lein/profiles.clj` to make this work?

**Comment by jaycfields** [comment]
You shouldn't. I have a basically blank laptop that I just ran it on and all was well.

**Comment by seancorfield** [comment]
I had to do `lein javac; lein jar`. I think part of the problem is that the JAR is getting created with old `cljx` output files in it.

I ran `lein do clean, javac, jar` and got a clean JAR that contained the `cljc` source (instead of the generated versions). When I `lein install` that and try to use it, I get a different exception:
```
Exception in thread "main" java.lang.ClassNotFoundException: cljs.analyzer, compiling:(expectations/platform.cljc:16:11)
```
And sure enough that line still refers to `cljs.analyzer` because of this function:
```
#?(:clj
   (defn expanding [n]
     (if (cljs?)
       `'~(cljs.analyzer/macroexpand-1 {} n)
       `'~(macroexpand-1 n))))
```
This was supposedly fixed by @plexus in #74 but clearly isn't. I also noticed that @magnars ran into the same problem I did with Java compilation when they tried to build from source.

**Comment by jaycfields** [comment]
I committed a complete guess if you want to give that a shot. If that doesn't work, we can always just ditch the cljs in that fn for now.

**Comment by seancorfield** [comment]
It doesn't look like your change passes `lein test`?

**Comment by jaycfields** [comment]
2.1.8 is out there now, and includes all of your changes from today.

**Comment by seancorfield** [comment]
Thanks. Confirmed 2.1.8 works in a Clojure-only project. I went ahead and updated `boot-expectations` to 1.0.8 to provide Expectations 2.1.8 by default. That also tests cleanly.

**Comment by jaycfields** [comment]
awesome, thx for all the help

**Comment by plexus** [comment]
sorry for the trouble!

**Comment by seancorfield** [comment]
No problem. My first opportunity to experiment with reader conditionals so it was time well spent :)
