### ISSUE TITLE
You can't expect "more" of an exception

### ISSUE THREAD

**Issue by seancorfield** [jaycfields/expectations#80]
If the actual expression throws (or returns) an exception, the only thing you can expect of it is an exception type, based on how the `compare-expr` multimethod works:

https://github.com/jaycfields/expectations/blob/master/src/cljc/expectations.cljc#L324-L346

If you throw `(ex-info "Something" my-data)`, it would be great to be able to "expect" something about the message and/or the `ex-data` but `compare-expr` doesn't allow you to run functions on an "actual-exception".

Looking at the code, I'm not sure how best to achieve this, without obscuring how actual exceptions are reported but I'm going to give it some thought this afternoon and see if I can come up with a suggestion...

**Comment by jaycfields** [comment]
@seancorfield thanks for bringing this up. I've always held the stance that you shouldn't need to test an exception message, and if you do, it's better to wrap it in a try catch and test it inline. 

That said, I'm not against merging this, but I don't think I'm convinced yet. With the change in the PR you'd be able to use a fn, but you wouldn't be able to do something like

```clj
(expect (more-of foo
                 fn? foo)
  (/ 12 0))
```

My instinct is that having something that only works for some cases is worse than forcing people to do explicit try catch.

I'm not sure though, I'll probably sleep on it. if you have any more thoughts on this, definitely please do let me know.

**Comment by seancorfield** [comment]
The following works for me:

    #?(:clj (expect (more-of ex
                             ArithmeticException ex
                             "Divide by zero" (.getMessage ex))
                    (/ 12 0)))

and the example you give correctly fails with `exception thrown by (let [ex (/ 12 0)] ex) is not fn?`

**Comment by jaycfields** [comment]
Interesting, I must have misread something. Thanks for pointing that out. I'll take a look again in the morning.

**Comment by seancorfield** [comment]
I added that `more-of` test (above) to the PR, just FYI.

**Comment by jaycfields** [comment]
merged and released in version 2.1.9

I still think people shouldn't test exception messages, but this ins't too invasive so I don't mind including it. :)

**Comment by seancorfield** [comment]
Well, it originally cropped up with code that throws a lot of `clojure.lang.ExceptionInfo` exceptions, using `ex-info`, so all the exceptions were the same type, and in several cases just testing `ex-data` wasn't enough to distinguish between different exceptions that could be thrown. And at that point it seemed like I had a lot of `try` / `catch` / `assoc` / `ex-data` / `.getMessage` boilerplate and I figured life would be so much easier if I could just `expect` things directly about the exception itself.

So, thank you, you've made my life much better!

**Comment by seancorfield** [comment]
FWIW, it seems the `more-of` approach works with 2.1.8 -- I didn't think to try that since I'd already started down the `more` path that did not work. I only just realized this (in testing another project this morning). So I think this change makes Expectations' behavior more consistent since you can now use `more` on exceptions in 2.1.9, just like you could use `more-of` previously.
